apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: demo-mtls
  namespace: demo
spec:
  host: "*.demo.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
