apiVersion: v1
kind: Pod
metadata:
  name: test-compliant
  namespace: demo
spec:
  securityContext:
    runAsNonRoot: true
  containers:
    - name: nginx
      image: nginxinc/nginx-unprivileged:1.25
      ports:
        - containerPort: 8080

