apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-apps-svcmonitor
  namespace: monitoring
  labels:
    release: kube-prom-stack
spec:
  namespaceSelector:
    matchNames:
      - prod-travelersources
  selector:
    matchLabels:
      metrics: "true"
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
      scheme: http  # plain HTTP works due to PERMISSIVE ok s
