apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace | default "dev" }}

spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit | default 2 }}

  selector:
    matchLabels:
      app: {{ .Chart.Name }}

  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: {{ .Chart.Name }}
        istio: monitor

    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}

          ports:
            - name: http
              containerPort: {{ .Values.service.port | default 80 }}
              protocol: TCP

          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | default "100m" }}
              memory: {{ .Values.resources.requests.memory | default "128Mi" }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | default "500m" }}
              memory: {{ .Values.resources.limits.memory | default "256Mi" }}

          {{- if .Values.envFromSecret }}
          envFrom:
            - secretRef:
                name: {{ .Values.envFromSecret }}
          {{- else if .Values.env }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          {{- end }}

  strategy:
    canary:
      stableService: {{ .Chart.Name }}-stable
      canaryService: {{ .Chart.Name }}-canary
      scaleDownDelaySeconds: {{ .Values.strategy.scaleDownDelaySeconds | default 60 }}

      trafficRouting:
        istio:
          virtualService:
            name: {{ .Chart.Name }}-vsvc
            routes:
              - primary

      steps:
        - setWeight: 10
        - setWeight: 20
        - pause:
            duration: 20s
        - setWeight: 30
        - pause:
            duration: 20s
        - setWeight: 40
        - pause:
            duration: 20s
        - setWeight: 50
        - pause:
            duration: 20s
        - setWeight: 60
        - pause:
            duration: 20s
        - setWeight: 70
        - pause:
            duration: 20s
        - setWeight: 80
        - pause:
            duration: 20s
        - setWeight: 90
        - pause:
            duration: 20s
