---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-secret
  namespace: demo
spec:
  encryptedData:
    JWT_SECRET: AgAE7ezQofkSY3Rj7ENoMFShWRvwt4MUqrEVZmfMM2yJ4o8RY0CbrBaCZljcyL6ff0BUnVsV8nIINbR9xExirSKlbrxqw5XmHnQ4MNwgykyGnt8SMpmmaAObXcKvSzUBIHsNStkY6swR7sKoBuvYMGc9JP6CuIknKNcCbCBbLDczyRyMplI9ZRVT99atHpmcidhyZL03d++YJK7xeAR2NnuhsKdU3spcYEdNqVhh4TuHDLkWqPF049DUWVQBpAxt2J1Wwce1raRTvXssJIyJUzvOTL3iKBKgmBp/p9k3sUyDnkZ2NlMM9dNH9YSINAOZAH94imZWmM65VcdLUGf5MoV+TZ0CP8yuzK6baNvHo1TiPp5YQ/D3aq1dnViC97DnK9qmPZc/ALRmrWlWFXpAUoSSdvMEX14JG61xEMoktlYFk6VywxEyhKxZQ1eLiXZv/u9ZKQsEfCmhfKGQiI8ATBRz9qaL0WlhtKkTBcuKqLdOKa8ZzvlpsZtSrh0VH0oyRx5BAD8i/i67LoVb1Drt79eJV7ZcSdtCfSFjZDNFO+clm42UnpmDHrG+62TwLz/5LDtuVUzzzHaiSfLWAS9FQ4mBLwSyMDu/BiSmxvpPCekSlpETTvgN0tl0W7VFYYyfYGiP/5e//uSl8bheuOy+8R4xbnqfCqz9+ZAg8oC7WxkL8dgPj2yiyubsdqAE/Wnhln5an/Ie0127G8hX
    PGPASSWORD: AgBYpDWRMkZYoadARxBo9HRYKqkqPG0aLy4YJOn2dlPc6Q6vK1ez1O36C4CaU8IyXArfD5kcgYbPPFl5upfTgPf59lfuZ35fUNXtAptduKW/dGkY4D+3ArJr26IwIhWRvCTg0Iqh75YASR8IhMeOFPJf+MAUdvS70qGe+O9J2TMkjb7qjUaAaGZzL9LV3FJ5bw7q+Z+6p6FkQ+8l/MtTJJIGbg2lAsI0nK0VFUtVOwaUzfwSs+j14n/ZrH1+IbETa0FKxo7xQzKxrzWI3jPA4N9gJRoCIixuoIOObpGfoBx8I4Pp/oR16O+nK0H6KSwEU8/nfT75+lK8CkMu3YH9lSGTJd5/Q3XPmZ9IswqcU0+oOychQJAN3sVJrdykZlDF9v6gclGW5vjyLVblRFrX87q2SB2hj/Ay3PnoiEZvbJ9OAyosLnv3yltD6v5Ln5aIrAZ4s97Pa8+DEroCNWz3odHzlKG2aoAql3mAjCyDC7fab0/tFGF91MzGAUTmknFijcHMhCgQJIezUSjcQN/EBeDJza+kCqwYKR6nYkNUCIDfHGf4q9y2862E2v7GJqYRI87V05Ucv25q+EbRfrchj/9B++UULkVZI7M/Ob7btSy+lpmsJWnLZDjx2rEZEB8+KQej2CsDZqiekCuUSYWM80Kk/Gw/tSXq3jRpyF3/f/SOyAcjTLTlxb8ejnc+sCytUk6dUNYMtQ79
  template:
    metadata:
      name: auth-secret
      namespace: demo
    type: Opaque
