apiVersion: v1
kind: Service
metadata:
  name: orders-canary
  namespace: demo
spec:
  ports:
  - port: 3004
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: orders

---
apiVersion: v1
kind: Service
metadata:
  name: orders-stable
  namespace: demo

spec:
  ports:
  - port: 3004
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: orders