apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-runasnonroot
spec:
  rules:
    - name: add-run-as-non-root
      match:
        resources:
          kinds:
            - Pod
      mutate:
        patchStrategicMerge:
          spec:
            securityContext:
              runAsNonRoot: true

