apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-local
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/amdevops989/ironality.com.git
    targetRevision: local
    path: gitops/apps/frontend/overlays/local
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

