apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: orders
  namespace: monitoring
  labels:
    release: kube-prom-stack   # MUST match your Prom stack
spec:
  namespaceSelector:
    matchNames:
      - demo
  selector:
    matchLabels:
      metrics: "true"
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s

