---
# Source: payments/templates/8-pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: payments-pdb
  namespace: demo
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: payments
---
# Source: payments/templates/5-configMap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-config
  namespace: demo
data:
  PGUSER: "appuser"
  PGHOST: "my-postgresql.postgres.svc.cluster.local"
  PGDATABASE: "mv100db"
  PGPORT: "5432"

  REDIS_URL: "redis-master.redis.svc.cluster.local:6379"

  KAFKA_BROKERS: "kafka.kafka.svc.cluster.local:9092"
  KAFKA_CLIENT_ID: "products-service"
  KAFKA_TOPIC_PRODUCTS: "mv100db.public.products"
  KAFKA_TOPIC_USERS: "mv100db.public.users"
  KAFKA_TOPIC_ORDERS: "mv100db.public.orders"
  KAFKA_TOPIC_PAYMENTS: "mv100db.public.payments"

  LOG_LEVEL: "info"
  PORT: "3005"
  FRONTEND_URL: "http://frontend.localdev.me"
  OTEL_PROM_PORT: "9468"
  ORDERS_SERVICE_URL: http://api.localdev.me:3004/orders
  SUCCESS_URL: http://frontend.localdev.me/success
  CANCEL_URL: http://frontend.localdev.me/cancel
---
# Source: payments/templates/6-dashboard-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-stable-dashboard
  namespace: monitoring
  labels:
    grafana_dashboard: "1"
    release: kube-prom-stack
data:
  payments-stable.json: |
    {
      "title": "payments-Stable DevOps Dashboard",
      "schemaVersion": 36,
      "version": 1,
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": "-- Grafana --",
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "panels": [
        {
          "type": "gauge",
          "title": "Success Rate",
          "gridPos": { "x": 0, "y": 0, "w": 12, "h": 6 },
          "datasource": "Prometheus",
          "targets": [
            {
              "expr": "(sum(rate(istio_requests_total{reporter=\"source\",destination_service_name=\"payments-stable\",response_code=~\"2..\"}[5m])) / sum(rate(istio_requests_total{reporter=\"source\",destination_service_name=\"payments-stable\"}[5m]))) * 100",
              "refId": "A"
            }
          ],
          "fieldConfig": { "defaults": { "unit": "percent" } }
        },
        {
          "type": "gauge",
          "title": "4xx Error Rate",
          "gridPos": { "x": 12, "y": 0, "w": 12, "h": 6 },
          "datasource": "Prometheus",
          "targets": [
            {
              "expr": "(sum(rate(istio_requests_total{reporter=\"source\",destination_service_name=\"payments-stable\",response_code=~\"4..\"}[5m])) / sum(rate(istio_requests_total{reporter=\"source\",destination_service_name=\"payments-stable\"}[5m]))) * 100",
              "refId": "B"
            }
          ],
          "fieldConfig": { "defaults": { "unit": "percent" } }
        },
        {
          "type": "gauge",
          "title": "5xx Error Rate",
          "gridPos": { "x": 0, "y": 6, "w": 12, "h": 6 },
          "datasource": "Prometheus",
          "targets": [
            {
              "expr": "(sum(rate(istio_requests_total{reporter=\"source\",destination_service_name=\"payments-stable\",response_code=~\"5..\"}[5m])) / sum(rate(istio_requests_total{reporter=\"source\",destination_service_name=\"payments-stable\"}[5m]))) * 100",
              "refId": "C"
            }
          ],
          "fieldConfig": { "defaults": { "unit": "percent" } }
        },
        {
          "type": "gauge",
          "title": "P95 Latency (ms)",
          "gridPos": { "x": 12, "y": 6, "w": 12, "h": 6 },
          "datasource": "Prometheus",
          "targets": [
            {
              "expr": "histogram_quantile(0.95, sum(rate(istio_request_duration_milliseconds_bucket{reporter=\"source\",destination_service_name=\"payments-stable\"}[5m])) by (le))",
              "refId": "D"
            }
          ],
          "fieldConfig": { "defaults": { "unit": "ms" } }
        },
        {
          "type": "gauge",
          "title": "CPU Usage (%)",
          "gridPos": { "x": 0, "y": 12, "w": 12, "h": 6 },
          "datasource": "Prometheus",
          "targets": [
            {
              "expr": "100 * sum(rate(container_cpu_usage_seconds_total{namespace=\"demo\",pod=~\"payments-.*\",container!=\"POD\"}[2m])) / sum(kube_pod_container_resource_limits{namespace=\"demo\",pod=~\"payments-.*\",container!=\"POD\",resource=\"cpu\"})",
              "refId": "E"
            }
          ],
          "fieldConfig": { "defaults": { "unit": "percent" } }
        },
        {
          "type": "gauge",
          "title": "Memory Usage (%)",
          "gridPos": { "x": 12, "y": 12, "w": 12, "h": 6 },
          "datasource": "Prometheus",
          "targets": [
            {
              "expr": "100 * sum(container_memory_working_set_bytes{namespace=\"demo\",pod=~\"payments-.*\",container!=\"POD\"}) / sum(kube_pod_container_resource_limits{namespace=\"demo\",pod=~\"payments-.*\",container!=\"POD\",resource=\"memory\"})",
              "refId": "F"
            }
          ],
          "fieldConfig": { "defaults": { "unit": "percent" } }
        },

        {
          "type": "stat",
          "title": "Checkout Sessions Created / min",
          "gridPos": { "x": 0, "y": 18, "w": 8, "h": 5 },
          "datasource": "Prometheus",
          "targets": [{ "expr": "sum(rate(checkout_sessions_created_total[5m])) * 60", "refId": "G" }]
        },
        {
          "type": "stat",
          "title": "Payments Succeeded / min",
          "gridPos": { "x": 8, "y": 18, "w": 8, "h": 5 },
          "datasource": "Prometheus",
          "targets": [{ "expr": "sum(rate(payments_succeeded_total[5m])) * 60", "refId": "H" }]
        },
        {
          "type": "stat",
          "title": "Payments Failed / min",
          "gridPos": { "x": 16, "y": 18, "w": 8, "h": 5 },
          "datasource": "Prometheus",
          "targets": [{ "expr": "sum(rate(payments_failed_total[5m])) * 60", "refId": "I" }]
        },
        {
          "type": "graph",
          "title": "Payment Amount P95",
          "gridPos": { "x": 0, "y": 23, "w": 24, "h": 6 },
          "datasource": "Prometheus",
          "targets": [{ "expr": "histogram_quantile(0.95,sum(rate(payment_amounts_bucket[5m])) by (le))", "refId": "J" }]
        }
      ]
    }
---
# Source: payments/templates/1-services.yaml
apiVersion: v1
kind: Service
metadata:
  name: payments-canary
  namespace: demo
spec:
  selector:
    app: payments
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005
      name: http
---
# Source: payments/templates/1-services.yaml
apiVersion: v1
kind: Service
metadata:
  name: payments-stable
  namespace: demo
spec:
  selector:
    app: payments
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005
      name: http
---
# Source: payments/templates/4-serviceMetrics.yaml
apiVersion: v1
kind: Service
metadata:
  name: payments-metrics
  namespace: demo
  labels:
    app: payments
    metrics: "true"
spec:
  selector:
    app: payments
  ports:
    - name: metrics
      port: 9468
      targetPort: 9468
      protocol: TCP
---
# Source: payments/templates/7-hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: payments-hpa
  namespace: demo
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: payments

  minReplicas: 1
  maxReplicas: 10

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
---
# Source: payments/templates/10-prometheus-rules.yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: payments-stable-rules
  namespace: monitoring
  labels:
    release: kube-prom-stack
spec:
  groups:
  - name: istio-frontend-alerts
    rules:

    # ----------------------------------------------------
    # 1. Stable Success Rate Alert (<95%)
    # ----------------------------------------------------
    - alert: IstioFrontendStableLowSuccessRate
      expr: |
        (sum(rate(istio_requests_total{
            reporter="destination",
            destination_service_name="payments-stable",
            namespace="demo"
        }[5m]))
        /
        sum(rate(istio_requests_total{
            reporter="destination",
            destination_service_name="payments-stable",
            namespace="demo"
        }[5m]))) * 100 < 95
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "payments-stable service success rate is low"
        description: "Success rate for payments-stable dropped below 95%."

    # ----------------------------------------------------
    # 2. Stable 5xx Error Rate Alert (>1%)
    # ----------------------------------------------------
    - alert: IstiopaymentsStableHigh5xxRate
      expr: |
        sum(rate(istio_requests_total{
            reporter="destination",
            destination_service_name="payments-stable",
            response_code=~"5..",
            namespace="demo"
        }[5m]))
        /
        sum(rate(istio_requests_total{
            reporter="destination",
            destination_service_name="payments-stable",
            namespace="demo"
        }[5m])) > 0.01
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "payments-stable service 5xx error rate is too high"
        description: "More than 1% of requests to payments-stable are 5xx errors."

    # ----------------------------------------------------
    # 3. Stable P95 Latency Alert (>500ms)
    # ----------------------------------------------------
    - alert: IstiopaymentsStableHighP95Latency
      expr: |
        histogram_quantile(
          0.95,
          sum(rate(istio_request_duration_milliseconds_bucket{
              reporter="destination",
              destination_service_name="payments-stable",
              namespace="demo"
          }[5m])) by (le)
        ) > 500
      for: 3m
      labels:
        severity: warning
      annotations:
        summary: "payments-stable service P95 latency is high"
        description: "P95 latency for payments-stable exceeded 500ms."
---
# Source: payments/templates/11-rollout.yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: payments
  namespace: demo
spec:
  replicas: 1
  revisionHistoryLimit: 1

  selector:
    matchLabels:
      app: payments

  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: payments
        istio: monitor
        metrics: "true"   ## to let prometheus scrap metrics in mtls mode 

    spec:
      containers:
        - name: payments
          image: "devopsflow999/payments:main-v0.1.4"
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: payments-config
            - secretRef:
                name: demo-secrets

          ports:
            - name: http
              containerPort: 3005
              protocol: TCP
            - name: metrics
              containerPort: 9468
              protocol: TCP

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi

  strategy:
      canary:
        stableService: payments-stable
        canaryService: payments-canary

        trafficRouting:
          istio:
            virtualService:
              name: payments-vsvc
              routes:
                - primary
        steps:
          - setWeight: 10
          - setWeight: 20
          - pause:
              duration: 20s
          - setWeight: 30
          - pause:
              duration: 20s
          - setWeight: 40
          - pause:
              duration: 20s
          - setWeight: 50
          - pause:
              duration: 20s
          - setWeight: 60
          - pause:
              duration: 20s
          - setWeight: 70
          - pause:
              duration: 20s
          - setWeight: 80
          - pause:
              duration: 20s
          - setWeight: 90
          - pause:
              duration: 20s
---
# Source: payments/templates/2-virtualservice.yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: payments-vsvc
  namespace: demo
spec:
  hosts:
    - "api.localdev.me"
  gateways:
    - "api-gateway"
  http:

    # Canary route
    - name: payments-canary-debug
      match:
        - uri:
            prefix: "/payments/"
          headers:
            x-canary:
              exact: "true"
        - uri:
            prefix: "/payments"
          headers:
            x-canary:
              exact: "true"
      route:
        - destination:
            host: payments-canary
            port:
              number: 3005
          weight: 100
      # corsPolicy:
      #   allowOrigins:
      #     - exact: "http://frontend.localdev.me"
      #   allowMethods: ["GET","POST","PUT","DELETE","OPTIONS"]
      #   allowHeaders: ["*"]
      #   allowCredentials: true
      #   maxAge: "1h"

    # Stable route
    - name: primary
      match:
        - uri:
            prefix: "/payments/"
        - uri:
            exact: "/payments"
        - uri:
            prefix: "/payments"
        - uri:
            exact: "/payments"
      route:
        - destination:
            host: payments-stable
            port:
              number: 3005
          weight: 100
        - destination:
            host: payments-canary
            port:
              number: 3005
          weight: 0
      # corsPolicy:
      #   allowOrigins:
      #     - exact: "http://frontend.localdev.me"
      #   allowMethods: ["GET","POST","PUT","DELETE","OPTIONS"]
      #   allowHeaders: ["*"]
      #   allowCredentials: true
      #   maxAge: "1h"
